---
# Bring stack down
- hosts: loadbalancer
  become: true
  tasks:
    - services: name=nginx statee=stopped
    - wait_for: port=80 state=drained # default state=started

- hosts: webserver
  become: true
  tasks:
    - services: name=apache2 statee=stopped
    - wait_for: port=80 state=stopped

# Restart mysql
- hosts: database
  become: true
  tasks:
    - service: name=mysql state=restarted
    - wait_for: port=3306 state=started

# Bring stack up
- hosts: webserver
  become: true
  tasks:
    - services: ame=apache2 statee=started
    - wait_for: port=80 # default state=started

- hosts: loadbalancer
  become: true
  tasks:
    - services: name=nginx statee=started
    - wait_for: port=80 # default state=started
